/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as SocRouteRouteImport } from './routes/soc/route'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAddressesRouteImport } from './routes/admin/addresses'
import { Route as AdminAlertsRouteImport } from './routes/admin/alerts'
import { Route as AdminApprovalsRouteImport } from './routes/admin/approvals'
import { Route as AdminAssetFlowsRouteImport } from './routes/admin/asset-flows'
import { Route as AdminAttackCasesRouteImport } from './routes/admin/attack-cases'
import { Route as AdminAuditLogsRouteImport } from './routes/admin/audit-logs'
import { Route as AdminContractsRouteImport } from './routes/admin/contracts'
import { Route as AdminDappsRouteImport } from './routes/admin/dapps'
import { Route as AdminRiskRulesRouteImport } from './routes/admin/risk-rules'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminTokensRouteImport } from './routes/admin/tokens'
import { Route as AdminUserAssetsRouteImport } from './routes/admin/user-assets'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminWalletSimulatorRouteImport } from './routes/admin/wallet-simulator'
import { Route as AdminWalletsRouteImport } from './routes/admin/wallets'
import { Route as LabSlugRouteImport } from './routes/lab.$slug'
import { Route as LabSecurityRouteImport } from './routes/lab.security'
import { Route as SocIndexRouteImport } from './routes/soc/index'
import { Route as SocAlertsRouteImport } from './routes/soc/alerts'
import { Route as SocApprovalsRouteImport } from './routes/soc/approvals'
import { Route as SocAttackChainRouteImport } from './routes/soc/attack-chain'
import { Route as SocAttackLibraryRouteImport } from './routes/soc/attack-library'
import { Route as SocAutoScanRouteImport } from './routes/soc/auto-scan'
import { Route as SocDashboardRouteImport } from './routes/soc/dashboard'
import { Route as AdminAlertRulesIndexRouteImport } from './routes/admin/alert-rules/index'
import { Route as AdminAuditLogIndexRouteImport } from './routes/admin/audit-log/index'
import { Route as AdminDefenseEngineIndexRouteImport } from './routes/admin/defense-engine/index'
import { Route as AdminFundFlowIndexRouteImport } from './routes/admin/fund-flow/index'
import { Route as AdminGovernanceIndexRouteImport } from './routes/admin/governance/index'
import { Route as AdminIntelligenceIndexRouteImport } from './routes/admin/intelligence/index'
import { Route as AdminProtocolRiskIndexRouteImport } from './routes/admin/protocol-risk/index'
import { Route as AdminSecuritySimulationsRouteImport } from './routes/admin/security/simulations'
import { Route as AdminThreatFeedIndexRouteImport } from './routes/admin/threat-feed/index'
import { Route as AdminUsdtSenderIndexRouteImport } from './routes/admin/usdt-sender/index'
import { Route as AdminWalletRiskIndexRouteImport } from './routes/admin/wallet-risk/index'
import { Route as LabSecuritySimulationRouteImport } from './routes/lab.security.simulation'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SocRouteRoute = SocRouteRouteImport.update({
  id: '/soc',
  path: '/soc',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAddressesRoute = AdminAddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAlertsRoute = AdminAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminApprovalsRoute = AdminApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAssetFlowsRoute = AdminAssetFlowsRouteImport.update({
  id: '/asset-flows',
  path: '/asset-flows',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAttackCasesRoute = AdminAttackCasesRouteImport.update({
  id: '/attack-cases',
  path: '/attack-cases',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminContractsRoute = AdminContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDappsRoute = AdminDappsRouteImport.update({
  id: '/dapps',
  path: '/dapps',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRiskRulesRoute = AdminRiskRulesRouteImport.update({
  id: '/risk-rules',
  path: '/risk-rules',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTokensRoute = AdminTokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUserAssetsRoute = AdminUserAssetsRouteImport.update({
  id: '/user-assets',
  path: '/user-assets',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminWalletSimulatorRoute = AdminWalletSimulatorRouteImport.update({
  id: '/wallet-simulator',
  path: '/wallet-simulator',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminWalletsRoute = AdminWalletsRouteImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => AdminRouteRoute,
} as any)
const LabSlugRoute = LabSlugRouteImport.update({
  id: '/lab/$slug',
  path: '/lab/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LabSecurityRoute = LabSecurityRouteImport.update({
  id: '/lab/security',
  path: '/lab/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SocIndexRoute = SocIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SocRouteRoute,
} as any)
const SocAlertsRoute = SocAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => SocRouteRoute,
} as any)
const SocApprovalsRoute = SocApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => SocRouteRoute,
} as any)
const SocAttackChainRoute = SocAttackChainRouteImport.update({
  id: '/attack-chain',
  path: '/attack-chain',
  getParentRoute: () => SocRouteRoute,
} as any)
const SocAttackLibraryRoute = SocAttackLibraryRouteImport.update({
  id: '/attack-library',
  path: '/attack-library',
  getParentRoute: () => SocRouteRoute,
} as any)
const SocAutoScanRoute = SocAutoScanRouteImport.update({
  id: '/auto-scan',
  path: '/auto-scan',
  getParentRoute: () => SocRouteRoute,
} as any)
const SocDashboardRoute = SocDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => SocRouteRoute,
} as any)
const AdminAlertRulesIndexRoute = AdminAlertRulesIndexRouteImport.update({
  id: '/alert-rules/',
  path: '/alert-rules/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAuditLogIndexRoute = AdminAuditLogIndexRouteImport.update({
  id: '/audit-log/',
  path: '/audit-log/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDefenseEngineIndexRoute = AdminDefenseEngineIndexRouteImport.update({
  id: '/defense-engine/',
  path: '/defense-engine/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFundFlowIndexRoute = AdminFundFlowIndexRouteImport.update({
  id: '/fund-flow/',
  path: '/fund-flow/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminGovernanceIndexRoute = AdminGovernanceIndexRouteImport.update({
  id: '/governance/',
  path: '/governance/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminIntelligenceIndexRoute = AdminIntelligenceIndexRouteImport.update({
  id: '/intelligence/',
  path: '/intelligence/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProtocolRiskIndexRoute = AdminProtocolRiskIndexRouteImport.update({
  id: '/protocol-risk/',
  path: '/protocol-risk/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSecuritySimulationsRoute =
  AdminSecuritySimulationsRouteImport.update({
    id: '/security/simulations',
    path: '/security/simulations',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminThreatFeedIndexRoute = AdminThreatFeedIndexRouteImport.update({
  id: '/threat-feed/',
  path: '/threat-feed/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsdtSenderIndexRoute = AdminUsdtSenderIndexRouteImport.update({
  id: '/usdt-sender/',
  path: '/usdt-sender/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminWalletRiskIndexRoute = AdminWalletRiskIndexRouteImport.update({
  id: '/wallet-risk/',
  path: '/wallet-risk/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const LabSecuritySimulationRoute = LabSecuritySimulationRouteImport.update({
  id: '/simulation',
  path: '/simulation',
  getParentRoute: () => LabSecurityRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/soc': typeof SocRouteRouteWithChildren
  '/admin/addresses': typeof AdminAddressesRoute
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/asset-flows': typeof AdminAssetFlowsRoute
  '/admin/attack-cases': typeof AdminAttackCasesRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/contracts': typeof AdminContractsRoute
  '/admin/dapps': typeof AdminDappsRoute
  '/admin/risk-rules': typeof AdminRiskRulesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tokens': typeof AdminTokensRoute
  '/admin/user-assets': typeof AdminUserAssetsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wallet-simulator': typeof AdminWalletSimulatorRoute
  '/admin/wallets': typeof AdminWalletsRoute
  '/lab/$slug': typeof LabSlugRoute
  '/lab/security': typeof LabSecurityRouteWithChildren
  '/soc/alerts': typeof SocAlertsRoute
  '/soc/approvals': typeof SocApprovalsRoute
  '/soc/attack-chain': typeof SocAttackChainRoute
  '/soc/attack-library': typeof SocAttackLibraryRoute
  '/soc/auto-scan': typeof SocAutoScanRoute
  '/soc/dashboard': typeof SocDashboardRoute
  '/admin/': typeof AdminIndexRoute
  '/soc/': typeof SocIndexRoute
  '/admin/security/simulations': typeof AdminSecuritySimulationsRoute
  '/lab/security/simulation': typeof LabSecuritySimulationRoute
  '/admin/alert-rules/': typeof AdminAlertRulesIndexRoute
  '/admin/audit-log/': typeof AdminAuditLogIndexRoute
  '/admin/defense-engine/': typeof AdminDefenseEngineIndexRoute
  '/admin/fund-flow/': typeof AdminFundFlowIndexRoute
  '/admin/governance/': typeof AdminGovernanceIndexRoute
  '/admin/intelligence/': typeof AdminIntelligenceIndexRoute
  '/admin/protocol-risk/': typeof AdminProtocolRiskIndexRoute
  '/admin/threat-feed/': typeof AdminThreatFeedIndexRoute
  '/admin/usdt-sender/': typeof AdminUsdtSenderIndexRoute
  '/admin/wallet-risk/': typeof AdminWalletRiskIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/addresses': typeof AdminAddressesRoute
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/asset-flows': typeof AdminAssetFlowsRoute
  '/admin/attack-cases': typeof AdminAttackCasesRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/contracts': typeof AdminContractsRoute
  '/admin/dapps': typeof AdminDappsRoute
  '/admin/risk-rules': typeof AdminRiskRulesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tokens': typeof AdminTokensRoute
  '/admin/user-assets': typeof AdminUserAssetsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wallet-simulator': typeof AdminWalletSimulatorRoute
  '/admin/wallets': typeof AdminWalletsRoute
  '/lab/$slug': typeof LabSlugRoute
  '/lab/security': typeof LabSecurityRouteWithChildren
  '/soc/alerts': typeof SocAlertsRoute
  '/soc/approvals': typeof SocApprovalsRoute
  '/soc/attack-chain': typeof SocAttackChainRoute
  '/soc/attack-library': typeof SocAttackLibraryRoute
  '/soc/auto-scan': typeof SocAutoScanRoute
  '/soc/dashboard': typeof SocDashboardRoute
  '/admin': typeof AdminIndexRoute
  '/soc': typeof SocIndexRoute
  '/admin/security/simulations': typeof AdminSecuritySimulationsRoute
  '/lab/security/simulation': typeof LabSecuritySimulationRoute
  '/admin/alert-rules': typeof AdminAlertRulesIndexRoute
  '/admin/audit-log': typeof AdminAuditLogIndexRoute
  '/admin/defense-engine': typeof AdminDefenseEngineIndexRoute
  '/admin/fund-flow': typeof AdminFundFlowIndexRoute
  '/admin/governance': typeof AdminGovernanceIndexRoute
  '/admin/intelligence': typeof AdminIntelligenceIndexRoute
  '/admin/protocol-risk': typeof AdminProtocolRiskIndexRoute
  '/admin/threat-feed': typeof AdminThreatFeedIndexRoute
  '/admin/usdt-sender': typeof AdminUsdtSenderIndexRoute
  '/admin/wallet-risk': typeof AdminWalletRiskIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/soc': typeof SocRouteRouteWithChildren
  '/admin/addresses': typeof AdminAddressesRoute
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/asset-flows': typeof AdminAssetFlowsRoute
  '/admin/attack-cases': typeof AdminAttackCasesRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/contracts': typeof AdminContractsRoute
  '/admin/dapps': typeof AdminDappsRoute
  '/admin/risk-rules': typeof AdminRiskRulesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tokens': typeof AdminTokensRoute
  '/admin/user-assets': typeof AdminUserAssetsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wallet-simulator': typeof AdminWalletSimulatorRoute
  '/admin/wallets': typeof AdminWalletsRoute
  '/lab/$slug': typeof LabSlugRoute
  '/lab/security': typeof LabSecurityRouteWithChildren
  '/soc/alerts': typeof SocAlertsRoute
  '/soc/approvals': typeof SocApprovalsRoute
  '/soc/attack-chain': typeof SocAttackChainRoute
  '/soc/attack-library': typeof SocAttackLibraryRoute
  '/soc/auto-scan': typeof SocAutoScanRoute
  '/soc/dashboard': typeof SocDashboardRoute
  '/admin/': typeof AdminIndexRoute
  '/soc/': typeof SocIndexRoute
  '/admin/security/simulations': typeof AdminSecuritySimulationsRoute
  '/lab/security/simulation': typeof LabSecuritySimulationRoute
  '/admin/alert-rules/': typeof AdminAlertRulesIndexRoute
  '/admin/audit-log/': typeof AdminAuditLogIndexRoute
  '/admin/defense-engine/': typeof AdminDefenseEngineIndexRoute
  '/admin/fund-flow/': typeof AdminFundFlowIndexRoute
  '/admin/governance/': typeof AdminGovernanceIndexRoute
  '/admin/intelligence/': typeof AdminIntelligenceIndexRoute
  '/admin/protocol-risk/': typeof AdminProtocolRiskIndexRoute
  '/admin/threat-feed/': typeof AdminThreatFeedIndexRoute
  '/admin/usdt-sender/': typeof AdminUsdtSenderIndexRoute
  '/admin/wallet-risk/': typeof AdminWalletRiskIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/soc'
    | '/admin/addresses'
    | '/admin/alerts'
    | '/admin/approvals'
    | '/admin/asset-flows'
    | '/admin/attack-cases'
    | '/admin/audit-logs'
    | '/admin/contracts'
    | '/admin/dapps'
    | '/admin/risk-rules'
    | '/admin/settings'
    | '/admin/tokens'
    | '/admin/user-assets'
    | '/admin/users'
    | '/admin/wallet-simulator'
    | '/admin/wallets'
    | '/lab/$slug'
    | '/lab/security'
    | '/soc/alerts'
    | '/soc/approvals'
    | '/soc/attack-chain'
    | '/soc/attack-library'
    | '/soc/auto-scan'
    | '/soc/dashboard'
    | '/admin/'
    | '/soc/'
    | '/admin/security/simulations'
    | '/lab/security/simulation'
    | '/admin/alert-rules/'
    | '/admin/audit-log/'
    | '/admin/defense-engine/'
    | '/admin/fund-flow/'
    | '/admin/governance/'
    | '/admin/intelligence/'
    | '/admin/protocol-risk/'
    | '/admin/threat-feed/'
    | '/admin/usdt-sender/'
    | '/admin/wallet-risk/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/addresses'
    | '/admin/alerts'
    | '/admin/approvals'
    | '/admin/asset-flows'
    | '/admin/attack-cases'
    | '/admin/audit-logs'
    | '/admin/contracts'
    | '/admin/dapps'
    | '/admin/risk-rules'
    | '/admin/settings'
    | '/admin/tokens'
    | '/admin/user-assets'
    | '/admin/users'
    | '/admin/wallet-simulator'
    | '/admin/wallets'
    | '/lab/$slug'
    | '/lab/security'
    | '/soc/alerts'
    | '/soc/approvals'
    | '/soc/attack-chain'
    | '/soc/attack-library'
    | '/soc/auto-scan'
    | '/soc/dashboard'
    | '/admin'
    | '/soc'
    | '/admin/security/simulations'
    | '/lab/security/simulation'
    | '/admin/alert-rules'
    | '/admin/audit-log'
    | '/admin/defense-engine'
    | '/admin/fund-flow'
    | '/admin/governance'
    | '/admin/intelligence'
    | '/admin/protocol-risk'
    | '/admin/threat-feed'
    | '/admin/usdt-sender'
    | '/admin/wallet-risk'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/soc'
    | '/admin/addresses'
    | '/admin/alerts'
    | '/admin/approvals'
    | '/admin/asset-flows'
    | '/admin/attack-cases'
    | '/admin/audit-logs'
    | '/admin/contracts'
    | '/admin/dapps'
    | '/admin/risk-rules'
    | '/admin/settings'
    | '/admin/tokens'
    | '/admin/user-assets'
    | '/admin/users'
    | '/admin/wallet-simulator'
    | '/admin/wallets'
    | '/lab/$slug'
    | '/lab/security'
    | '/soc/alerts'
    | '/soc/approvals'
    | '/soc/attack-chain'
    | '/soc/attack-library'
    | '/soc/auto-scan'
    | '/soc/dashboard'
    | '/admin/'
    | '/soc/'
    | '/admin/security/simulations'
    | '/lab/security/simulation'
    | '/admin/alert-rules/'
    | '/admin/audit-log/'
    | '/admin/defense-engine/'
    | '/admin/fund-flow/'
    | '/admin/governance/'
    | '/admin/intelligence/'
    | '/admin/protocol-risk/'
    | '/admin/threat-feed/'
    | '/admin/usdt-sender/'
    | '/admin/wallet-risk/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  SocRouteRoute: typeof SocRouteRouteWithChildren
  LabSlugRoute: typeof LabSlugRoute
  LabSecurityRoute: typeof LabSecurityRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soc': {
      id: '/soc'
      path: '/soc'
      fullPath: '/soc'
      preLoaderRoute: typeof SocRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/addresses': {
      id: '/admin/addresses'
      path: '/addresses'
      fullPath: '/admin/addresses'
      preLoaderRoute: typeof AdminAddressesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/alerts': {
      id: '/admin/alerts'
      path: '/alerts'
      fullPath: '/admin/alerts'
      preLoaderRoute: typeof AdminAlertsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/approvals': {
      id: '/admin/approvals'
      path: '/approvals'
      fullPath: '/admin/approvals'
      preLoaderRoute: typeof AdminApprovalsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/asset-flows': {
      id: '/admin/asset-flows'
      path: '/asset-flows'
      fullPath: '/admin/asset-flows'
      preLoaderRoute: typeof AdminAssetFlowsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/attack-cases': {
      id: '/admin/attack-cases'
      path: '/attack-cases'
      fullPath: '/admin/attack-cases'
      preLoaderRoute: typeof AdminAttackCasesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/audit-logs': {
      id: '/admin/audit-logs'
      path: '/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/contracts': {
      id: '/admin/contracts'
      path: '/contracts'
      fullPath: '/admin/contracts'
      preLoaderRoute: typeof AdminContractsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/dapps': {
      id: '/admin/dapps'
      path: '/dapps'
      fullPath: '/admin/dapps'
      preLoaderRoute: typeof AdminDappsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/risk-rules': {
      id: '/admin/risk-rules'
      path: '/risk-rules'
      fullPath: '/admin/risk-rules'
      preLoaderRoute: typeof AdminRiskRulesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/tokens': {
      id: '/admin/tokens'
      path: '/tokens'
      fullPath: '/admin/tokens'
      preLoaderRoute: typeof AdminTokensRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/user-assets': {
      id: '/admin/user-assets'
      path: '/user-assets'
      fullPath: '/admin/user-assets'
      preLoaderRoute: typeof AdminUserAssetsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/wallet-simulator': {
      id: '/admin/wallet-simulator'
      path: '/wallet-simulator'
      fullPath: '/admin/wallet-simulator'
      preLoaderRoute: typeof AdminWalletSimulatorRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/wallets': {
      id: '/admin/wallets'
      path: '/wallets'
      fullPath: '/admin/wallets'
      preLoaderRoute: typeof AdminWalletsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/lab/$slug': {
      id: '/lab/$slug'
      path: '/lab/$slug'
      fullPath: '/lab/$slug'
      preLoaderRoute: typeof LabSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/security': {
      id: '/lab/security'
      path: '/lab/security'
      fullPath: '/lab/security'
      preLoaderRoute: typeof LabSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soc/': {
      id: '/soc/'
      path: '/'
      fullPath: '/soc/'
      preLoaderRoute: typeof SocIndexRouteImport
      parentRoute: typeof SocRouteRoute
    }
    '/soc/alerts': {
      id: '/soc/alerts'
      path: '/alerts'
      fullPath: '/soc/alerts'
      preLoaderRoute: typeof SocAlertsRouteImport
      parentRoute: typeof SocRouteRoute
    }
    '/soc/approvals': {
      id: '/soc/approvals'
      path: '/approvals'
      fullPath: '/soc/approvals'
      preLoaderRoute: typeof SocApprovalsRouteImport
      parentRoute: typeof SocRouteRoute
    }
    '/soc/attack-chain': {
      id: '/soc/attack-chain'
      path: '/attack-chain'
      fullPath: '/soc/attack-chain'
      preLoaderRoute: typeof SocAttackChainRouteImport
      parentRoute: typeof SocRouteRoute
    }
    '/soc/attack-library': {
      id: '/soc/attack-library'
      path: '/attack-library'
      fullPath: '/soc/attack-library'
      preLoaderRoute: typeof SocAttackLibraryRouteImport
      parentRoute: typeof SocRouteRoute
    }
    '/soc/auto-scan': {
      id: '/soc/auto-scan'
      path: '/auto-scan'
      fullPath: '/soc/auto-scan'
      preLoaderRoute: typeof SocAutoScanRouteImport
      parentRoute: typeof SocRouteRoute
    }
    '/soc/dashboard': {
      id: '/soc/dashboard'
      path: '/dashboard'
      fullPath: '/soc/dashboard'
      preLoaderRoute: typeof SocDashboardRouteImport
      parentRoute: typeof SocRouteRoute
    }
    '/admin/alert-rules/': {
      id: '/admin/alert-rules/'
      path: '/alert-rules'
      fullPath: '/admin/alert-rules/'
      preLoaderRoute: typeof AdminAlertRulesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/audit-log/': {
      id: '/admin/audit-log/'
      path: '/audit-log'
      fullPath: '/admin/audit-log/'
      preLoaderRoute: typeof AdminAuditLogIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/defense-engine/': {
      id: '/admin/defense-engine/'
      path: '/defense-engine'
      fullPath: '/admin/defense-engine/'
      preLoaderRoute: typeof AdminDefenseEngineIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/fund-flow/': {
      id: '/admin/fund-flow/'
      path: '/fund-flow'
      fullPath: '/admin/fund-flow/'
      preLoaderRoute: typeof AdminFundFlowIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/governance/': {
      id: '/admin/governance/'
      path: '/governance'
      fullPath: '/admin/governance/'
      preLoaderRoute: typeof AdminGovernanceIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/intelligence/': {
      id: '/admin/intelligence/'
      path: '/intelligence'
      fullPath: '/admin/intelligence/'
      preLoaderRoute: typeof AdminIntelligenceIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/protocol-risk/': {
      id: '/admin/protocol-risk/'
      path: '/protocol-risk'
      fullPath: '/admin/protocol-risk/'
      preLoaderRoute: typeof AdminProtocolRiskIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/security/simulations': {
      id: '/admin/security/simulations'
      path: '/security/simulations'
      fullPath: '/admin/security/simulations'
      preLoaderRoute: typeof AdminSecuritySimulationsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/threat-feed/': {
      id: '/admin/threat-feed/'
      path: '/threat-feed'
      fullPath: '/admin/threat-feed/'
      preLoaderRoute: typeof AdminThreatFeedIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/usdt-sender/': {
      id: '/admin/usdt-sender/'
      path: '/usdt-sender'
      fullPath: '/admin/usdt-sender/'
      preLoaderRoute: typeof AdminUsdtSenderIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/wallet-risk/': {
      id: '/admin/wallet-risk/'
      path: '/wallet-risk'
      fullPath: '/admin/wallet-risk/'
      preLoaderRoute: typeof AdminWalletRiskIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/lab/security/simulation': {
      id: '/lab/security/simulation'
      path: '/simulation'
      fullPath: '/lab/security/simulation'
      preLoaderRoute: typeof LabSecuritySimulationRouteImport
      parentRoute: typeof LabSecurityRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAddressesRoute: typeof AdminAddressesRoute
  AdminAlertsRoute: typeof AdminAlertsRoute
  AdminApprovalsRoute: typeof AdminApprovalsRoute
  AdminAssetFlowsRoute: typeof AdminAssetFlowsRoute
  AdminAttackCasesRoute: typeof AdminAttackCasesRoute
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminContractsRoute: typeof AdminContractsRoute
  AdminDappsRoute: typeof AdminDappsRoute
  AdminRiskRulesRoute: typeof AdminRiskRulesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTokensRoute: typeof AdminTokensRoute
  AdminUserAssetsRoute: typeof AdminUserAssetsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWalletSimulatorRoute: typeof AdminWalletSimulatorRoute
  AdminWalletsRoute: typeof AdminWalletsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminSecuritySimulationsRoute: typeof AdminSecuritySimulationsRoute
  AdminAlertRulesIndexRoute: typeof AdminAlertRulesIndexRoute
  AdminAuditLogIndexRoute: typeof AdminAuditLogIndexRoute
  AdminDefenseEngineIndexRoute: typeof AdminDefenseEngineIndexRoute
  AdminFundFlowIndexRoute: typeof AdminFundFlowIndexRoute
  AdminGovernanceIndexRoute: typeof AdminGovernanceIndexRoute
  AdminIntelligenceIndexRoute: typeof AdminIntelligenceIndexRoute
  AdminProtocolRiskIndexRoute: typeof AdminProtocolRiskIndexRoute
  AdminThreatFeedIndexRoute: typeof AdminThreatFeedIndexRoute
  AdminUsdtSenderIndexRoute: typeof AdminUsdtSenderIndexRoute
  AdminWalletRiskIndexRoute: typeof AdminWalletRiskIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAddressesRoute: AdminAddressesRoute,
  AdminAlertsRoute: AdminAlertsRoute,
  AdminApprovalsRoute: AdminApprovalsRoute,
  AdminAssetFlowsRoute: AdminAssetFlowsRoute,
  AdminAttackCasesRoute: AdminAttackCasesRoute,
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminContractsRoute: AdminContractsRoute,
  AdminDappsRoute: AdminDappsRoute,
  AdminRiskRulesRoute: AdminRiskRulesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTokensRoute: AdminTokensRoute,
  AdminUserAssetsRoute: AdminUserAssetsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWalletSimulatorRoute: AdminWalletSimulatorRoute,
  AdminWalletsRoute: AdminWalletsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminSecuritySimulationsRoute: AdminSecuritySimulationsRoute,
  AdminAlertRulesIndexRoute: AdminAlertRulesIndexRoute,
  AdminAuditLogIndexRoute: AdminAuditLogIndexRoute,
  AdminDefenseEngineIndexRoute: AdminDefenseEngineIndexRoute,
  AdminFundFlowIndexRoute: AdminFundFlowIndexRoute,
  AdminGovernanceIndexRoute: AdminGovernanceIndexRoute,
  AdminIntelligenceIndexRoute: AdminIntelligenceIndexRoute,
  AdminProtocolRiskIndexRoute: AdminProtocolRiskIndexRoute,
  AdminThreatFeedIndexRoute: AdminThreatFeedIndexRoute,
  AdminUsdtSenderIndexRoute: AdminUsdtSenderIndexRoute,
  AdminWalletRiskIndexRoute: AdminWalletRiskIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface SocRouteRouteChildren {
  SocAlertsRoute: typeof SocAlertsRoute
  SocApprovalsRoute: typeof SocApprovalsRoute
  SocAttackChainRoute: typeof SocAttackChainRoute
  SocAttackLibraryRoute: typeof SocAttackLibraryRoute
  SocAutoScanRoute: typeof SocAutoScanRoute
  SocDashboardRoute: typeof SocDashboardRoute
  SocIndexRoute: typeof SocIndexRoute
}

const SocRouteRouteChildren: SocRouteRouteChildren = {
  SocAlertsRoute: SocAlertsRoute,
  SocApprovalsRoute: SocApprovalsRoute,
  SocAttackChainRoute: SocAttackChainRoute,
  SocAttackLibraryRoute: SocAttackLibraryRoute,
  SocAutoScanRoute: SocAutoScanRoute,
  SocDashboardRoute: SocDashboardRoute,
  SocIndexRoute: SocIndexRoute,
}

const SocRouteRouteWithChildren = SocRouteRoute._addFileChildren(
  SocRouteRouteChildren,
)

interface LabSecurityRouteChildren {
  LabSecuritySimulationRoute: typeof LabSecuritySimulationRoute
}

const LabSecurityRouteChildren: LabSecurityRouteChildren = {
  LabSecuritySimulationRoute: LabSecuritySimulationRoute,
}

const LabSecurityRouteWithChildren = LabSecurityRoute._addFileChildren(
  LabSecurityRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  SocRouteRoute: SocRouteRouteWithChildren,
  LabSlugRoute: LabSlugRoute,
  LabSecurityRoute: LabSecurityRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
